### ISSUE TITLE
Consider contributing to the inspec supported repo

### ISSUE THREAD

**Issue by brandonjbjelland** [martezr/inspec-gcp#6]
Hey there @martezr -

I wanted to make sure it was on your radar that https://github.com/inspec/inspec-gcp is also an actively developed project trying to fill this space. It'd be excellent if you could bring some of your ideas to contribute over there.

Thanks for your work in this space. It's badly needed!

**Comment by martezr** [comment]
@brandoconnor Thanks for the heads up and I have actually been in contact with the developers for the official InSpec GCP project which was based upon some of the work from my original code base. I need to update this repo with a deprecated notification. I'll definitely be looking to contribute to the official project as well.
